apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-handlers
  labels:
    app: synapse-handlers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse-handlers
  template:
    metadata:
      labels:
        app: synapse-handlers
    spec:
      containers:
      - name: main-container
        image: synapse-handlers:latest       
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: synapse-handler-service
spec:
  selector:
    app: synapse-handlers
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000